apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-test-analizator
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: load-analizator.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: load-test-analizator
            port:
              number: 80
