apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: app
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_BUCKET_NAME: "diploma-load-reports"
  AWS_REGION: "ru-central1"
  AWS_S3_ENDPOINT: "https://storage.yandexcloud.net"
  AWS_S3_FORCE_PATH_STYLE: "true"
