name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH key for VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.APP_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.APP_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        run: |
          cat > infra/ansible/inventory.ini <<EOF
[app]
diploma-app-vm ansible_host=${{ secrets.APP_VM_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
EOF

      - name: Create Ansible config
        working-directory: infra/ansible
        run: |
          cat > ansible.cfg <<EOF
[defaults]
inventory = ./inventory.ini
host_key_checking = False
retry_files_enabled = False
EOF

      - name: Run deploy playbook
        working-directory: infra/ansible
        run: |
          ansible-playbook deploy_app.yml

