name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r load-test-analizator/requirements.txt
          pip install flake8 pytest

      - name: Run flake8
        run: |
          cd load-test-analizator
          flake8 .

      - name: Run pytest
        run: |
          cd load-test-analizator
          pytest

      - name: Build Docker image
        run: |
          cd load-test-analizator
          docker build -t load-test-analizator:test-ci .

      - name: Configure YC CLI
        run: |
          echo "${{ secrets.YC_PRIVATE_KEY }}" > yc-key.json
          sudo apt-get install -y jq
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          yc config set service-account-key yc-key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Login to Yandex Container Registry
        run: |
          yc container registry configure-docker

      - name: Push Docker image to YCR
        run: |
          cd load-test-analizator
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma:latest .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma:latest
